import '../models/agent.dart';
import '../models/product.dart';

class SeedData {
  static final products = <Product>[
    Product(
      id: 'pads_whisper_ultra_clean_xl_plus',
      name: 'Whisper Ultra Clean XL+',
      brand: 'Whisper',
      category: ProductCategory.sanitaryPads,
      description: 'Whisper Ultra Clean XL+ pads are designed for heavy flow days, featuring a nearly 40% longer design and a wider back for superior coverage.',
      highlights: ['40 pads value pack', 'XL+ size (317mm)', 'Dri-Weave top sheet', 'Heavy flow protection'],
      attributes: ['40 pads', 'XL+', '317mm'],
      mrp: 499,
      salePrice: 449,
      stockCount: 140,
      rating: 4.8,
      reviewCount: 328,
      isAvailable: true,
      isBestSeller: true,
      tileColor: 0xFFF7D9E3,
      imageUrl: 'https://images.weserv.nl/?url=https://m.media-amazon.com/images/I/51+u7D1rB+L._AC_SL1000_.jpg',
    ),
    Product(
      id: 'pads_whisper_bindazz_nights',
      name: 'Whisper Bindazz Nights',
      brand: 'Whisper',
      category: ProductCategory.sanitaryPads,
      description: 'Whisper Bindazz Nights XXXL pads offer 0% leaks all night long with a 75% wider back.',
      highlights: ['10 pads pack', 'XXXL size (400mm)', 'Double Hug Wings', 'All-night protection'],
      attributes: ['10 pads', 'XXXL', '400mm'],
      mrp: 189,
      salePrice: 169,
      stockCount: 92,
      rating: 4.6,
      reviewCount: 164,
      isAvailable: true,
      tileColor: 0xFFF2D6EE,
      imageUrl: 'https://images.weserv.nl/?url=https://m.media-amazon.com/images/I/61Nl5g3W+tL.jpg',
    ),
    Product(
      id: 'pads_stayfree_secure_xl_wings',
      name: 'Stayfree Secure XL Wings',
      brand: 'Stayfree',
      category: ProductCategory.sanitaryPads,
      description: 'Stayfree Secure XL with wings offers extra length and wings for added security and protection.',
      highlights: ['28 pads pack', 'XL size with wings', 'Cottony soft comfort', 'Deep channels'],
      attributes: ['28 pads', 'XL Wings', 'Cottony Soft'],
      mrp: 249,
      salePrice: 219,
      stockCount: 118,
      rating: 4.3,
      reviewCount: 138,
      isAvailable: true,
      tileColor: 0xFFFBE8EF,
      imageUrl: 'https://images.weserv.nl/?url=https://m.media-amazon.com/images/I/61Moyj6XOnL._SL1500_.jpg',
    ),
    Product(
      id: 'pads_sofy_antibacterial',
      name: 'Sofy Anti Bacterial',
      brand: 'Sofy',
      category: ProductCategory.sanitaryPads,
      description: 'Sofy Anti Bacteria pads feature a unique Herbal Shield to provide 99.9% antibacterial protection.',
      highlights: ['40 pads pack', 'Extra long (290mm)', 'Herbal Shield protection', 'Antibacterial'],
      attributes: ['40 pads', 'Anti-Bacterial', '290mm'],
      mrp: 299,
      salePrice: 269,
      stockCount: 76,
      rating: 4.7,
      reviewCount: 102,
      isAvailable: true,
      isNew: true,
      tileColor: 0xFFFCE7E0,
      imageUrl: 'https://images.weserv.nl/?url=https://m.media-amazon.com/images/I/61X-p1nL-tL._SL1500_.jpg',
    ),
    Product(
      id: 'baby_pampers_active_nb',
      name: 'Pampers Active Baby NB',
      brand: 'Pampers',
      category: ProductCategory.babyDiapers,
      description: 'Pampers Active Baby Taped Diapers for Newborns provide up to 12 hours of dryness.',
      highlights: ['72 diapers mega pack', 'Newborn (Up to 5kg)', 'Taped style', 'Magic Gel tech'],
      attributes: ['72 diapers', 'Newborn', 'Taped'],
      mrp: 849,
      salePrice: 749,
      stockCount: 96,
      rating: 4.8,
      reviewCount: 251,
      isAvailable: true,
      isBestSeller: true,
      tileColor: 0xFFDFF1F7,
      imageUrl: 'https://images.weserv.nl/?url=https://m.media-amazon.com/images/I/71NoyV8fFLL.jpg',
    ),
    Product(
      id: 'baby_mamypoko_extra_absorb_m',
      name: 'MamyPoko Extra Absorb M',
      brand: 'MamyPoko',
      category: ProductCategory.babyDiapers,
      description: 'MamyPoko Pants Extra Absorb with its Criss-Cross Absorbent Sheet spreads urine equally.',
      highlights: ['64 pants value pack', 'Medium (7 to 12kg)', 'Criss-Cross Sheet', '12 hours absorbency'],
      attributes: ['64 pants', 'Medium', 'Pull-up'],
      mrp: 799,
      salePrice: 699,
      stockCount: 109,
      rating: 4.8,
      reviewCount: 233,
      isAvailable: true,
      isBestSeller: true,
      tileColor: 0xFFFFE6D7,
      imageUrl: 'https://images.weserv.nl/?url=https://m.media-amazon.com/images/I/61wFoy6XvjL._SL1500_.jpg',
    ),
    Product(
      id: 'adult_friends_premium_m',
      name: 'Friends Premium Adult M',
      brand: 'Friends',
      category: ProductCategory.adultDiapers,
      description: 'Friends Adult Diaper Premium Taped style provide high absorbency and an anti-bacterial core.',
      highlights: ['20 diapers pack', 'Medium (28" to 44")', '10-12 hours protection', 'Tape-style fastening'],
      attributes: ['20 diapers', 'Medium', 'Tape style'],
      mrp: 649,
      salePrice: 549,
      stockCount: 91,
      rating: 4.7,
      reviewCount: 172,
      isAvailable: true,
      isBestSeller: true,
      tileColor: 0xFFF0EDF3,
      imageUrl: 'https://images.weserv.nl/?url=https://m.media-amazon.com/images/I/71oJ3D05p5L._SL1500_.jpg',
    ),
    Product(
      id: 'adult_dignity_overnight_xl',
      name: 'Dignity Overnight XL',
      brand: 'Dignity',
      category: ProductCategory.adultDiapers,
      description: 'Dignity Overnight Adult Diapers size XL provide maximum protection for long hours and overnight.',
      highlights: ['10 diapers pack', 'XL (38" to 59")', 'Overnight protection', 'Cloth-like back sheet'],
      attributes: ['10 diapers', 'XL', 'Tape style'],
      mrp: 699,
      salePrice: 599,
      stockCount: 59,
      rating: 4.6,
      reviewCount: 83,
      isAvailable: true,
      tileColor: 0xFFECE7F7,
      imageUrl: 'https://images.weserv.nl/?url=https://m.media-amazon.com/images/I/71t-u6XvjHL._SL1500_.jpg',
    ),
  ];

  static const agents = <Agent>[
    Agent(id: 'agent_asha_rathod', name: 'Asha Rathod', phone: '9876543210', area: 'Vatva', isActive: true, deliveriesCompleted: 41),
    Agent(id: 'agent_megha_patel', name: 'Megha Patel', phone: '9898989898', area: 'Nikol', isActive: true, deliveriesCompleted: 33),
  ];

  static const ngoPartners = <Map<String, String>>[
    {'name': 'Naroda Women Shelter', 'type': 'Women Shelter', 'area': 'Naroda'},
    {'name': 'Ahmedabad Elder Care Trust', 'type': 'Elder Care', 'area': 'Maninagar'},
  ];
}
